[package]
name = "libsynchro-apps"
version = "0.1.0"
edition = "2021"


[dependencies]
libsynchro = { version = "0.1.0", path = "../libsynchro" }
arr_macro = "0.1.3"
rand = "0.8.5"

[[bin]]
name = "atomic-exps"
path = "atomic-exps.rs"
doc = false